# upload sample file
# curl -X PUT http://localhost:8012/upload/wella       --form file=@hello.txt
PUT http://localhost:8014/upload/test-container
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="hello.txt"

< hello.txt
--WebAppBoundary--

###

# upload many files
PUT http://localhost:8014/v1/uploadMany/test-container
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="hello.txt"

< hello.txt
--WebAppBoundary--

###

#list files if test-container
GET http://localhost:8014/list/test-container
