server:
  port: 8014

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 25MB

azure:
  accountName: testdocsstorage
  accountKey: ${ACCOUNT_KEY}
  endpoint: https://${azure.accountName}.blob.core.windows.net
  maxFileSize: 20

#Add as environment variable for encrypted properties
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
